### PR TITLE
change to use multi erc20 trace for vk generation

### PR DESCRIPTION
**Pull request by DreamWuGit**

### CODE REVIEW

**Comment by lispc** [comment]
common-rs will be used by roller-rs.  If we read a file with path "./tests/traces/multiple-erc20.json", roller needs to put this file along side the execution binary... seems a bit complex.. I recalled that is why i chose empty circuit

**Comment by HAOYUatHZ** [comment]
we can embed this into rust code (in  common-rs).

**Comment by DreamWuGit** [comment]
> we can embed this into rust code (in common-rs) using "Raw string literal".

@HAOYUatHZ  you mean put content of multiple-erc20.json into code like following ?:
```
let multiple-erc20_trace = "{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockTrace": {
            "number": "0x8b",
            "hash": "0x435c3791f12cb7c0a47c73ade4d173d6ab7ad2fc97a2803474e534dd1c469e55",
            "gasLimit": 7698532,
            "difficulty": "0x2",
            "baseFee": "0x129",";
            ..........
```

it is doable,  BTW, this file is large (about 90000 lines)

**Comment by HAOYUatHZ** [comment]
> > we can embed this into rust code (in common-rs) using "Raw string literal".
> 
> @HAOYUatHZ you mean put content of multiple-erc20.json into code like following ?:
> 
> ```
> let multiple-erc20_trace = "{
>     "jsonrpc": "2.0",
>     "id": 1,
>     "result": {
>         "blockTrace": {
>             "number": "0x8b",
>             "hash": "0x435c3791f12cb7c0a47c73ade4d173d6ab7ad2fc97a2803474e534dd1c469e55",
>             "gasLimit": 7698532,
>             "difficulty": "0x2",
>             "baseFee": "0x129",";
>             ..........
> ```

yes like

```
r#'abcd
efg
'
```


> it is doable, BTW, this file is large (about 90000 lines)

yes, but I tink you can put it into a single file like mock_data.rs
and
```
pub mod mock_data
```

or somrthing

**Comment by DreamWuGit** [comment]
updated in [780a8a9](https://github.com/scroll-tech/common-rs/pull/67/commits/780a8a9f291298f585e05387eb85416fd888eb6c) to avoid read file from path.

**Comment by lispc** [comment]
i use include! macro here.  https://github.com/scroll-tech/common-rs/pull/68 seems much cleaner

**Comment by HAOYUatHZ** [comment]
so, should we merge #68 first then #67?

**Comment by zhuoatscroll** [comment]
> "./tests/traces/multiple-erc20.json",

merge #67 after mason finished mock proving mainnet blocks

**Pull request closed without merging**
