### PR TITLE
test: add more traces & bump `zkevm-circuits` version

### PR DESCRIPTION
**Pull request by HAOYUatHZ**
## MasterChef
+ `opcode 0xfe not defined`
+ `error` should be string instead of map?

## DAO
STATICCALL `codeList` encoding error

## NFT
**evm_circuit** fails
```
[2022-06-21T05:30:10Z WARN  zkevm_circuits::evm_circuit::witness] unimplemented opcode NOT
[2022-06-21T05:30:10Z WARN  zkevm_circuits::evm_circuit::witness] unimplemented opcode NOT
[2022-06-21T05:30:10Z WARN  zkevm_circuits::evm_circuit::witness] unimplemented opcode NOT
[2022-06-21T05:30:10Z WARN  zkevm_circuits::evm_circuit::witness] unimplemented opcode NOT
[2022-06-21T05:30:10Z WARN  zkevm_circuits::evm_circuit::witness] unimplemented opcode NOT
[2022-06-21T05:30:10Z WARN  zkevm_circuits::evm_circuit::witness] unimplemented opcode NOT
[2022-06-21T05:30:10Z INFO  zkevm::prover] Create evm proof of block 0xd3a3…1463
test test_evm_prove_verify ... FAILED

failures:

---- test_evm_prove_verify stdout ----
thread 'test_evm_prove_verify' panicked at 'Execution state unknown: DUMMY', /home/haoyu/.cargo/git/checkouts/zkevm-circuits-462c2cba34f9b301/16f6951/zkevm-circuits/src/evm_circuit/execution.rs:891:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/core/src/panicking.rs:106:14
   2: zkevm_circuits::evm_circuit::execution::ExecutionConfig<F>::assign_exec_step_int
   3: zkevm_circuits::evm_circuit::execution::ExecutionConfig<F>::assign_exec_step
   4: zkevm_circuits::evm_circuit::execution::ExecutionConfig<F>::assign_block::{{closure}}
   5: <halo2_proofs::circuit::floor_planner::single_pass::SingleChipLayouter<F,CS> as halo2_proofs::circuit::Layouter<F>>::assign_region
   6: zkevm_circuits::evm_circuit::execution::ExecutionConfig<F>::assign_block
   7: <zkevm_circuits::evm_circuit::test::TestCircuit<F> as halo2_proofs::plonk::circuit::Circuit<F>>::synthesize
   8: <halo2_proofs::circuit::floor_planner::single_pass::SimpleFloorPlanner as halo2_proofs::plonk::circuit::FloorPlanner>::synthesize
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  11: core::iter::adapters::process_results
  12: zkevm::prover::Prover::create_evm_proof
  13: core::ops::function::FnOnce::call_once
  14: core::ops::function::FnOnce::call_once
             at /rustc/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**state_circuit** passes

### CODE REVIEW

**Comment by lispc** [comment]
fixing nft evm circuit

**Comment by HAOYUatHZ** [comment]
> how to upgrade zkevm to fix nft evm circuit:
> 
> ```
> sed -i 's#rev = "16f6951c"#rev = "4797a964"#' setup/Cargo.toml types/Cargo.toml zkevm/Cargo.toml
> ```
> 
> @HAOYUatHZ

OK

**Comment by lispc** [comment]
zzhang will have a look at why MasterChef failed

**Comment by HAOYUatHZ** [comment]
```
make again
```
[ ] cat 0624.dao.evm.txt
[x] cat 0624.dao.state.txt
[x] cat 0624.nft.evm.txt
[x] cat 0624.nft.state.txt
[ ] cat 0624.sushi.evm.txt
[x] cat 0624.sushi.state.txt
---

**Comment by lispc** [comment]
fixing this

**Comment by lispc** [comment]
uograded.      https://github.com/scroll-tech/zkevm-circuits/pull/158

**Pull request merged**
